"use client";

import { useState } from "react";

interface ContentBlock {
  type: "paragraph" | "heading" | "subheading" | "list" | "note" | "step-list";
  text?: string;
  items?: string[];
}

interface Subsection {
  id: string;
  title: string;
  content: ContentBlock[];
}

interface DocSection {
  id: string;
  title: string;
  subsections: Subsection[];
}

const docSections: DocSection[] = [
  {
    id: "my-pipelines",
    title: "My Pipelines",
    subsections: [
      {
        id: "pipelines-overview",
        title: "Purpose and Audience",
        content: [
          {
            type: "paragraph",
            text: "Use the My Pipelines dashboard to discover, filter, and act on infrastructure pipelines across cloud providers. It's designed for platform engineers, DevOps practitioners, and developers who manage lifecycle actions (create, export, diff, open, rename, delete) and monitor deployment status.",
          },
        ],
      },
      {
        id: "high-level-overview",
        title: "High-level Overview",
        content: [
          {
            type: "heading",
            text: "Global Controls",
          },
          {
            type: "list",
            items: [
              "Search Pipelines: Quickly locate pipelines by name or keyword. Supports incremental narrowing of results as you type.",
              "Provider Filter (All, AWS, Azure, GCP): Toggle between All, AWS, Azure, and GCP to focus on a specific cloud context or view everything at once.",
              "Create Pipeline: Starts a guided flow to define and initialize a new pipeline. Use this when onboarding a service or provisioning new infrastructure.",
              "Pipeline Overview: Displays total pipeline count.",
              "Main Table: Lists pipelines with columns for Name, Provider, Description, Deployment Status, Created At, and Actions.",
            ],
          },
        ],
      },
      {
        id: "key-ui-elements",
        title: "Key UI Elements",
        content: [
          {
            type: "heading",
            text: "Pipeline List and Columns",
          },
          {
            type: "list",
            items: [
              "Pipeline Name: Primary identifier, expandable to reveal version/context-specific actions (Export, Open in Canvas, Pipeline Diff, Delete). When a Pipeline is edited and saved with new changes, the Version increments from V1 to V2.",
              "Provider: Cloud vendor associated with the pipeline (e.g., GCP). Helpful for sorting and scoping operational tasks.",
              "Description: Optional free-text context. Add concise, actionable descriptions to assist teammates with discoverability and intent.",
              "Deployment Status: Operational state such as Destroyed or Pending. Use this to triage attention—Pending may need monitoring; Destroyed indicates teardown complete.",
              "Created At: Timestamp of pipeline creation for auditing and lifecycle insights.",
              "Actions: Common per-row actions include Rename for quick retitling; expanded rows surface additional actions.",
            ],
          },
        ],
      },
      {
        id: "common-actions",
        title: "Common Actions and When to Use Them",
        content: [
          {
            type: "list",
            items: [
              "Rename: Apply clear, human-readable names to improve searchability and reduce confusion with autogenerated identifiers.",
              "Export: Capture the pipeline definition or artifact for backups, reviews, or migrations between environments.",
              "Open in Canvas: Visualize the pipeline topology to validate architecture, dependencies, and resource relationships. It will open in New Pipeline Canvas.",
              "Pipeline Diff: Compare versions to understand what changed before approving updates or rollbacks.",
              "Delete: Remove obsolete pipelines after teardown to keep the inventory clean and reduce operational noise.",
            ],
          },
        ],
      },
      {
        id: "operational-workflow",
        title: "Operational Workflow (Suggested)",
        content: [
          {
            type: "step-list",
            items: [
              "Search or filter to narrow to the relevant cloud provider and target pipeline.",
              "Expand the pipeline row to access version-specific actions and artifacts.",
              "Run Pipeline Diff to verify changes; if acceptable, proceed with your deployment workflow.",
              "Use Open in Canvas to visually validate dependencies and architecture.",
              "Export for backup or review, then apply/monitor until the desired status is reached.",
            ],
          },
        ],
      },
      {
        id: "troubleshooting-tips",
        title: "Troubleshooting and Tips",
        content: [
          {
            type: "list",
            items: [
              "Pending for too long: Check pipeline logs, validate credentials/permissions, and ensure provider quotas are sufficient.",
              "Destroyed but resources remain: Confirm finalizers/cleanup hooks, and reconcile via provider console to detect stragglers.",
              "Inconsistent names: Standardize via Rename and update references in downstream systems to avoid broken links.",
            ],
          },
        ],
      },
      {
        id: "pipelines-faq",
        title: "FAQ",
        content: [
          {
            type: "heading",
            text: "Frequently Asked Questions",
          },
          {
            type: "list",
            items: [
              "How do I quickly find all GCP pipelines? Use the Provider Filter and select GCP. Combine with the search bar to further narrow by name or keyword.",
              "When should I use Pipeline Diff? Before any apply/update operation. Diffs surface resource adds, deletes, and changes so you can approve with confidence.",
              "Is it safe to delete a pipeline once it shows Destroyed? Yes, if you've verified teardown is complete and no dependent services require the artifacts. Consider exporting the definition before deletion for audit history.",
            ],
          },
        ],
      },
    ],
  },
  {
    id: "manage-users",
    title: "Manage Users",
    subsections: [
      {
        id: "user-management-overview",
        title: "User Management Overview",
        content: [
          {
            type: "paragraph",
            text: "The Manage Users page allows organization admins to view, filter, and control access for all users in the workspace. From here, admins can track invitation status, manage pending invites, and review basic user details and send invitations.",
          },
          {
            type: "heading",
            text: "Page Header",
          },
          {
            type: "list",
            items: [
              "Total users: Count of all users and invitations associated with the current organization/project.",
              "Invite User button: Opens the user invitation flow to add new users by email.",
              "Accepted: Number of users who have accepted their invitations and are active.",
              "Pending: Number of invitations that have been sent but not yet accepted.",
            ],
          },
        ],
      },
      {
        id: "filters-and-search",
        title: "Filters and Search",
        content: [
          {
            type: "paragraph",
            text: "To help quickly find specific users or invitations, the page provides several filtering options.",
          },
          {
            type: "list",
            items: [
              "Search by Email or Username: A search box labeled 'Filter by email or username…'. Supports partial matches to quickly locate a specific user or invited email.",
              "Status Filter: A dropdown to filter by invitation/user status: All Users, Pending Only, Accepted Only, Expired Only, Cancelled Only.",
              "Clear Filters: A Clear button resets all filters and search terms back to the default view (All Users).",
            ],
          },
        ],
      },
      {
        id: "user-list",
        title: "User List",
        content: [
          {
            type: "paragraph",
            text: "The main table lists all users and invitations with the following columns:",
          },
          {
            type: "list",
            items: [
              "Full Name: Displays the user's full name or the name associated with the invitation.",
              "Email: The email address used for the account or invitation. A copy icon is available to quickly copy the email to the clipboard.",
              "Status: Indicates the current state of the user or invite — Pending, Accepted, Expired, or Cancelled.",
              "Group / Role: Shows the group or role assignment for the user (e.g., 'Org Admin', 'No assignment'). Helps understand what level of access each user has.",
              "Invited Date: The date and time when the invitation was originally sent. Useful for tracking old or stale invitations.",
              "Actions: Contextual actions depending on the status — Cancel for Pending invitations; Resend for Accepted users.",
            ],
          },
        ],
      },
      {
        id: "typical-admin-workflows",
        title: "Typical Admin Workflows",
        content: [
          {
            type: "paragraph",
            text: "From the Manage Users page, admins can:",
          },
          {
            type: "list",
            items: [
              "Invite new users using the Invite User button.",
              "Monitor onboarding progress by checking how many invitations are Accepted vs Pending.",
              "Clean up stale invitations by filtering to Pending Only or Expired Only and using Cancel in the Actions column.",
              "Verify access by checking each user's Group / Role and updating assignments elsewhere as needed.",
            ],
          },
        ],
      },
      {
        id: "invite-users-popup",
        title: "Invite Users Popup",
        content: [
          {
            type: "paragraph",
            text: "When a user clicks the Invite User button on the Manage Users page, the Invite Users to InfraGlide popup opens. This dialog lets admins invite one or more users to the organization and optionally assign them to access groups before sending the invitation.",
          },
          {
            type: "heading",
            text: "Invite Modes",
          },
          {
            type: "list",
            items: [
              "Bulk Invite: Used to invite multiple users at once. Each email address is entered on a separate line in the Email Addresses (one per line)* text area.",
              "Single User: Used when inviting one specific user. Provides a single email field and may show additional per-user details.",
            ],
          },
          {
            type: "heading",
            text: "Initial Group Assignment",
          },
          {
            type: "list",
            items: [
              "No Group (invite only): Users are invited without any group assignment. Users will have no access until an admin assigns them to groups later.",
              "Assign to Group: Allows the admin to choose one or more predefined access groups from the Select a group dropdown. The selected group(s) determine the permissions and scope the invited users will have once they join.",
            ],
          },
          {
            type: "heading",
            text: "Sending Invitations",
          },
          {
            type: "list",
            items: [
              "Cancel: Closes the popup without sending any invitations.",
              "Send Invitations (N): Sends invitations to all valid email addresses entered. The button label includes the count of invitations that will be sent.",
            ],
          },
          {
            type: "note",
            text: "After clicking Send Invitations, each listed email address receives an email invitation to join InfraGlide containing a link where the recipient can Accept or Deny the invitation.",
          },
        ],
      },
    ],
  },
  {
    id: "hub",
    title: "Hub",
    subsections: [
      {
        id: "hub-overview",
        title: "Hub Overview",
        content: [
          {
            type: "paragraph",
            text: "The Pipeline Hub is the central catalog where users can browse, discover, and manage reusable cloud infrastructure pipelines across providers such as AWS, Azure, and GCP. It provides a single view of all validated pipelines in an organization, ensuring teams can quickly find and reuse approved infrastructure definitions instead of creating them from scratch.",
          },
          {
            type: "heading",
            text: "Key Capabilities",
          },
          {
            type: "list",
            items: [
              "Central Catalog of Pipelines: Lists all available pipelines with metadata such as Pipeline Name, Cloud Provider, Description, and Creation Date / Version.",
              "Multiple versions per pipeline (e.g., Version 1), enabling safe iteration and upgrades.",
              "Filtering and Search: Global search bar to look up pipelines by name or keyword. Filter control to narrow pipelines by cloud provider (All, AWS, Azure, GCP).",
              "Sorting options on key columns (Pipeline Name, Provider, Description, Created At).",
              "Pipeline Details: Each pipeline row can be expanded to view its versions and associated metadata.",
            ],
          },
        ],
      },
      {
        id: "hub-implementation-flow",
        title: "Hub Implementation Flow",
        content: [
          {
            type: "step-list",
            items: [
              "Onboarding Pipelines into the Hub: Pipelines available in My Pipelines appear here based on the cloud provider, with details including Provider (AWS / Azure / GCP), human-readable name, short description and tags, and initial version.",
              "Discovering Pipelines: Users navigate to Hub from the left navigation panel. The Available Pipelines list shows all pipelines that match the active provider filter.",
              "Selecting a Pipeline: Click the row to expand version information, or check the selection box beside the pipeline. Review version information to ensure the correct release is chosen.",
            ],
          },
        ],
      },
      {
        id: "publishing-a-selected-pipeline",
        title: "Publishing a Selected Pipeline",
        content: [
          {
            type: "paragraph",
            text: "Once a pipeline is selected from the Hub, it can be published to GitHub. When a pipeline is published, it is pushed to the configured Git repository. Publishing ensures that the latest approved version of the pipeline definition is stored and version-controlled in Git, making it reusable and traceable.",
          },
          {
            type: "heading",
            text: "Publishing Workflow",
          },
          {
            type: "step-list",
            items: [
              "Pipeline Selection: The user identifies the pipeline they want to promote and selects the appropriate version from the expanded details.",
              "Publish Action: The user triggers the Publish action via the Publish button. The system validates pipeline definition integrity, provider configuration, and mandatory metadata.",
              "Post-Publish Management: Once published, a notification is shown as Published. Teams can roll forward to newer versions or keep using a stable published version.",
            ],
          },
        ],
      },
      {
        id: "pipeline-publishing-status",
        title: "Pipeline Publishing – Status Indicators",
        content: [
          {
            type: "paragraph",
            text: "After a publish action, the UI shows a clear status indicator for each pipeline:",
          },
          {
            type: "list",
            items: [
              "Green Tick – Published Successfully: The pipeline was published to the Git repository without errors. The latest version in the UI is in sync with the version stored in Git.",
              "Red Cross – Publish Failed: The attempt to publish the pipeline to Git failed. Possible reasons include Git connectivity or authentication issues, branch or repository configuration problems, and validation errors in the pipeline definition.",
              "Yellow Warning – Changes After Publish: The pipeline was previously published successfully, but the pipeline definition has since been modified in the UI, and those new changes have not yet been published to Git.",
            ],
          },
          {
            type: "note",
            text: "When a Yellow Warning appears, review the new changes and re-publish to sync the latest version to Git.",
          },
        ],
      },
    ],
  },
  {
    id: "architecture",
    title: "Architecture",
    subsections: [
      {
        id: "architecture-diagrams",
        title: "Architecture Diagrams",
        content: [
          {
            type: "paragraph",
            text: "The Architecture Diagrams page provides a visual view of pipeline architectures along with key metadata and technical details. It is designed for both quick inspection and deeper analysis of how a pipeline is structured and deployed.",
          },
          {
            type: "heading",
            text: "Select Pipeline",
          },
          {
            type: "paragraph",
            text: "At the top of the page, users can select a pipeline from the Select Pipeline dropdown. A cloud provider filter (All / AWS / Azure / GCP) helps narrow down the list.",
          },
          {
            type: "list",
            items: [
              "Pipeline Information: Name, Provider, Region, Status, and Deployment Status.",
              "Architecture Statistics: Total Components, Connections, Version, and Complexity indicator.",
              "Component Breakdown: Categorized view of major component types (e.g., Database, Compute, Storage) and their counts.",
            ],
          },
        ],
      },
      {
        id: "architecture-capture",
        title: "Architecture Capture",
        content: [
          {
            type: "paragraph",
            text: "The Architecture Capture section allows users to generate visual documentation of the pipeline.",
          },
          {
            type: "list",
            items: [
              "Capture Architecture: Takes a high-quality snapshot of the current pipeline architecture directly from the designer canvas. Downloads an image of the architecture diagram and saves it with the pipeline name for use in documentation, reports, or reviews.",
              "View in Designer: Opens the selected pipeline in the Designer view in a new page. Shows the full pipeline on an interactive canvas. Allows users to visually inspect, review, and modify components, connections, and configuration.",
            ],
          },
        ],
      },
      {
        id: "architecture-overview",
        title: "Architecture Overview",
        content: [
          {
            type: "paragraph",
            text: "The Architecture Overview section summarizes the structure and flow of the pipeline:",
          },
          {
            type: "list",
            items: [
              "Component Summary: A short description or label representing the Resource information.",
              "Connection Flow: A concise view of how components are connected end-to-end. If no connections are defined, the page will explicitly indicate that.",
            ],
          },
        ],
      },
      {
        id: "technical-specifications",
        title: "Technical Specifications",
        content: [
          {
            type: "paragraph",
            text: "The Technical Specifications panel provides low-level metadata useful for governance, auditing, and support:",
          },
          {
            type: "list",
            items: [
              "Pipeline ID: System-generated identifier for the pipeline.",
              "Created: Date when the pipeline was first created.",
              "Last Modified: Date when the pipeline was last updated.",
            ],
          },
          {
            type: "note",
            text: "These details help teams track pipeline lifecycle and changes over time.",
          },
        ],
      },
    ],
  },
  {
    id: "rbac-management",
    title: "RBAC Management",
    subsections: [
      {
        id: "rbac-overview",
        title: "Role-Based Access Control",
        content: [
          {
            type: "paragraph",
            text: "Manage access with ease using the RBAC system, designed to give you precise control over users, groups, and permissions.",
          },
          {
            type: "heading",
            text: "Key Features",
          },
          {
            type: "list",
            items: [
              "Centralized RBAC Control: Manage all access from a single, unified platform.",
              "Group-Based Access Management: Assign roles to groups and scale permissions effortlessly.",
              "Custom Role Policies: Define flexible roles tailored to your workflows.",
              "Automatic Permission Inheritance: Assign once and let access cascade across resources.",
              "Scalable & Easy to Manage: Add or remove users without reconfiguring permissions.",
              "Clear Visibility & Auditing: Instantly see who has access to what and why.",
            ],
          },
        ],
      },
      {
        id: "users-groups",
        title: "Principals (Users & Groups)",
        content: [
          {
            type: "paragraph",
            text: "Principals define who can access the system. They can be individual users or groups of users. Using groups is recommended, as it makes access management easier, more scalable, and more organized.",
          },
          {
            type: "heading",
            text: "Why Use Groups? (Best Practice)",
          },
          {
            type: "list",
            items: [
              "Easier Management: Grant role to group once, all members inherit access.",
              "Scalable: Add/remove users from groups without touching role assignments.",
              "Auditable: Clear which teams have access to which resources.",
              "Avoid: Assigning roles directly to individual users (hard to maintain).",
            ],
          },
        ],
      },
      {
        id: "roles",
        title: "Roles",
        content: [
          {
            type: "paragraph",
            text: "The platform provides roles that define what actions users or groups can perform, making it easy to manage permissions across your system.",
          },
          {
            type: "heading",
            text: "System Roles",
          },
          {
            type: "paragraph",
            text: "The platform provides default system roles such as Admin, Editor, and Viewer, designed to cover common access needs. These predefined roles allow you to quickly assign appropriate permissions without additional configuration.",
          },
          {
            type: "heading",
            text: "Custom Roles",
          },
          {
            type: "paragraph",
            text: "Users also have the flexibility to create custom roles tailored to specific requirements. Custom roles enable you to define precise permission sets that align with your organization's workflows.",
          },
          {
            type: "heading",
            text: "How to Create a Custom Role",
          },
          {
            type: "step-list",
            items: [
              "Click on the + New button in the Roles section.",
              "Enter the role name and description.",
              "Define the required role policies.",
              "Import permissions from existing roles like Admin, Editor, or Viewer.",
              "The custom role can now be assigned like any system role.",
            ],
          },
        ],
      },
      {
        id: "groups",
        title: "Groups",
        content: [
          {
            type: "paragraph",
            text: "Organize users into groups for easier access management.",
          },
          {
            type: "heading",
            text: "Complete Access Flow",
          },
          {
            type: "step-list",
            items: [
              "Create Groups: e.g., 'DevOps Team', 'FinOps Analysts'.",
              "Add Users to Groups: alice@company.com → DevOps Team.",
              "Define Role Policies (Role Policies tab): Create custom roles like 'Editor - Pipeline Focus'.",
              "Grant Access (User Assignments tab): Assign role to group on resource — DevOps Team → Editor - Pipeline Focus → Folder: Production.",
              "Result: All DevOps Team members can now deploy pipelines in Production folder and all its projects.",
            ],
          },
          {
            type: "heading",
            text: "Creating New Groups",
          },
          {
            type: "step-list",
            items: [
              "Click on the Create Group button in the Groups section.",
              "Enter the Group name and Description.",
              "Click on Create Group to save the new group.",
              "Click on Add Members to add users to the group.",
            ],
          },
        ],
      },
      {
        id: "assignments",
        title: "Principal Assignments",
        content: [
          {
            type: "paragraph",
            text: "Grant roles to users and groups for your organization, folders, or projects.",
          },
          {
            type: "heading",
            text: "How to Grant Access",
          },
          {
            type: "step-list",
            items: [
              "Click on Grant Access in User Assignments.",
              "Fill the Grant Access form with the required information.",
            ],
          },
        ],
      },
      {
        id: "user-access",
        title: "User Access",
        content: [
          {
            type: "paragraph",
            text: "Select a user to view their detailed access report. This shows all roles and permissions assigned to that user across all resources, groups, and projects.",
          },
        ],
      },
    ],
  },
  {
    id: "hld",
    title: "HLD - High Level Design",
    subsections: [
      {
        id: "hld-overview",
        title: "HLD Overview",
        content: [
          {
            type: "paragraph",
            text: "The High Level Design (HLD) view provides an executive summary and business overview for managers. It shows a high-level architectural view of your infrastructure pipelines across cloud providers.",
          },
          {
            type: "heading",
            text: "Key Features",
          },
          {
            type: "list",
            items: [
              "Pipeline Filtering: Filter pipelines by name, provider, or other attributes.",
              "Provider Support: View HLD across AWS, Azure, and GCP infrastructure.",
              "Executive Dashboard: High-level view suitable for management review and reporting.",
            ],
          },
        ],
      },
    ],
  },
  {
    id: "lld",
    title: "LLD - Low Level Design",
    subsections: [
      {
        id: "lld-overview",
        title: "LLD Overview",
        content: [
          {
            type: "paragraph",
            text: "The Low Level Design (LLD) view provides technical specifications and detailed implementation information for developers. It displays granular infrastructure details and component-level configurations.",
          },
          {
            type: "heading",
            text: "Key Features",
          },
          {
            type: "list",
            items: [
              "Pipeline Filtering: Filter pipelines by name, provider, or other attributes.",
              "Provider Support: Detailed technical views across AWS, Azure, and GCP infrastructure.",
              "Developer Dashboard: Low-level technical view suitable for implementation and debugging.",
            ],
          },
        ],
      },
    ],
  },
  {
    id: "credentials",
    title: "Credentials",
    subsections: [
      {
        id: "credentials-overview",
        title: "Credentials Overview",
        content: [
          {
            type: "paragraph",
            text: "Manage your cloud provider credentials from a central location. The Credentials section allows you to securely store and manage authentication details for AWS, Azure, and GCP.",
          },
          {
            type: "heading",
            text: "Key Features",
          },
          {
            type: "list",
            items: [
              "Create New Credentials: Add new cloud provider credentials with provider-specific configuration.",
              "Secure Storage: Credentials are stored securely and never exposed in plain text.",
              "Provider Support: Manage credentials for AWS, Azure, and GCP from a single interface.",
            ],
          },
        ],
      },
    ],
  },
  {
    id: "deployed-resources",
    title: "Deployed Resources",
    subsections: [
      {
        id: "deployed-resources-overview",
        title: "Deployed Resources Overview",
        content: [
          {
            type: "paragraph",
            text: "Monitor and manage your cloud infrastructure inventory for Google Cloud and other providers. The Deployed Resources view gives you a real-time inventory of all resources deployed through InfraGlide pipelines.",
          },
          {
            type: "heading",
            text: "Key Features",
          },
          {
            type: "list",
            items: [
              "Real-time Inventory: View all currently deployed cloud resources.",
              "Resource Details: See provider, region, status, and resource type for each deployed resource.",
              "Pipeline Association: Track which pipeline deployed each resource.",
            ],
          },
        ],
      },
    ],
  },
  {
    id: "cost-optimization",
    title: "Cost Optimization",
    subsections: [
      {
        id: "cost-optimization-overview",
        title: "Cost Optimization Overview",
        content: [
          {
            type: "paragraph",
            text: "One-click recommendations to optimize your cloud infrastructure costs. InfraGlide analyzes your deployed resources and provides actionable cost-saving recommendations.",
          },
          {
            type: "heading",
            text: "Key Features",
          },
          {
            type: "list",
            items: [
              "Automated Recommendations: AI-driven analysis of your infrastructure to identify cost-saving opportunities.",
              "Pipeline Cost View: See cost breakdown per pipeline and provider.",
              "One-click Optimization: Apply recommendations with a single click.",
            ],
          },
        ],
      },
    ],
  },
];

function renderContent(blocks: ContentBlock[]) {
  return blocks.map((block, idx) => {
    switch (block.type) {
      case "paragraph":
        return (
          <p key={idx} className="mb-4 text-indigo-200/65 leading-relaxed">
            {block.text}
          </p>
        );
      case "heading":
        return (
          <h4 key={idx} className="mt-6 mb-3 font-nacelle text-[0.95rem] font-semibold text-gray-200">
            {block.text}
          </h4>
        );
      case "subheading":
        return (
          <h5 key={idx} className="mt-4 mb-2 text-sm font-semibold text-gray-300">
            {block.text}
          </h5>
        );
      case "list":
        return (
          <ul key={idx} className="mb-4 space-y-2">
            {block.items?.map((item, i) => (
              <li key={i} className="flex gap-2 text-sm text-indigo-200/65">
                <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-indigo-500" />
                <span>{item}</span>
              </li>
            ))}
          </ul>
        );
      case "step-list":
        return (
          <ol key={idx} className="mb-4 space-y-2">
            {block.items?.map((item, i) => (
              <li key={i} className="flex gap-3 text-sm text-indigo-200/65">
                <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-indigo-500/20 text-xs font-bold text-indigo-400">
                  {i + 1}
                </span>
                <span className="leading-relaxed">{item}</span>
              </li>
            ))}
          </ol>
        );
      case "note":
        return (
          <div
            key={idx}
            className="my-4 rounded-lg border border-indigo-500/20 bg-indigo-500/10 px-4 py-3"
          >
            <p className="text-sm text-indigo-200/80">{block.text}</p>
          </div>
        );
      default:
        return null;
    }
  });
}

export default function DocsContent() {
  const [activeSection, setActiveSection] = useState<string>(docSections[0].id);
  const [activeSubsection, setActiveSubsection] = useState<number>(0);

  const currentSection = docSections.find((s) => s.id === activeSection);

  return (
    <div className="mx-auto max-w-6xl px-4 sm:px-6">
      <div className="py-12 md:py-20">
        {/* Page header */}
        <div className="mx-auto max-w-3xl pb-10 text-center">
          <div className="inline-flex items-center gap-3 pb-3 before:h-px before:w-8 before:bg-linear-to-r before:from-transparent before:to-indigo-200/50 after:h-px after:w-8 after:bg-linear-to-l after:from-transparent after:to-indigo-200/50">
            <span className="inline-flex bg-linear-to-r from-indigo-500 to-indigo-200 bg-clip-text text-transparent">
              Documentation
            </span>
          </div>
          <h1 className="animate-[gradient_6s_linear_infinite] bg-[linear-gradient(to_right,var(--color-gray-200),var(--color-indigo-200),var(--color-gray-50),var(--color-indigo-300),var(--color-gray-200))] bg-[length:200%_auto] bg-clip-text pb-4 font-nacelle text-3xl font-semibold text-transparent md:text-4xl">
            Everything you need to know about InfraGlide
          </h1>
          <p className="text-lg text-indigo-200/65">
            Comprehensive guides and references for managing cloud infrastructure with InfraGlide.
          </p>
        </div>

        {/* Docs layout */}
        <div className="grid grid-cols-1 gap-8 lg:grid-cols-4">
          {/* Sidebar */}
          <aside className="lg:col-span-1">
            <nav className="sticky top-24 space-y-1">
              {docSections.map((section) => (
                <div key={section.id}>
                  <button
                    onClick={() => {
                      if (activeSection === section.id) {
                        // keep it open; just reset subsection
                        setActiveSubsection(0);
                      } else {
                        setActiveSection(section.id);
                        setActiveSubsection(0);
                      }
                    }}
                    className={`w-full rounded-lg px-3 py-2 text-left text-sm font-semibold transition-colors ${
                      activeSection === section.id
                        ? "bg-indigo-500/20 text-indigo-300"
                        : "text-gray-400 hover:bg-gray-800/50 hover:text-gray-200"
                    }`}
                  >
                    {section.title}
                  </button>

                  {activeSection === section.id && (
                    <div className="ml-3 mt-1 space-y-0.5 border-l border-indigo-500/20 pl-3">
                      {section.subsections.map((sub, idx) => (
                        <button
                          key={sub.id}
                          onClick={() => setActiveSubsection(idx)}
                          className={`block w-full rounded px-2 py-1.5 text-left text-xs transition-colors ${
                            activeSubsection === idx
                              ? "font-semibold text-indigo-300"
                              : "text-gray-500 hover:text-gray-300"
                          }`}
                        >
                          {sub.title}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </nav>
          </aside>

          {/* Main content */}
          <main className="lg:col-span-2">
            {currentSection && (
              <div>
                <div className="mb-8">
                  <h2 className="font-nacelle text-2xl font-semibold text-gray-200 md:text-3xl">
                    {currentSection.title}
                  </h2>
                  <div className="mt-2 h-0.5 w-16 bg-linear-to-r from-indigo-500 to-indigo-200" />
                </div>

                <div className="space-y-10">
                  {currentSection.subsections.map((subsection, idx) => (
                    <article
                      key={subsection.id}
                      id={subsection.id}
                      className={`rounded-2xl p-6 transition-all ${
                        activeSubsection === idx
                          ? "bg-linear-to-br from-gray-900/80 via-gray-800/30 to-gray-900/80 ring-1 ring-indigo-500/20"
                          : "bg-linear-to-br from-gray-900/40 via-gray-800/10 to-gray-900/40"
                      }`}
                    >
                      <h3
                        className={`mb-4 font-nacelle text-lg font-semibold transition-colors ${
                          activeSubsection === idx ? "text-indigo-300" : "text-gray-200"
                        }`}
                      >
                        {subsection.title}
                      </h3>
                      <div>{renderContent(subsection.content)}</div>
                    </article>
                  ))}
                </div>
              </div>
            )}
          </main>

          {/* Right sidebar – On This Page */}
          <aside className="lg:col-span-1">
            <div className="sticky top-24 rounded-2xl bg-linear-to-br from-gray-900/50 via-gray-800/25 to-gray-900/50 p-5 before:pointer-events-none before:absolute before:inset-0 before:rounded-[inherit] before:border before:border-transparent before:[background:linear-gradient(to_right,var(--color-gray-800),var(--color-gray-700),var(--color-gray-800))_border-box] relative before:[mask:linear-gradient(white_0_0)_padding-box,_linear-gradient(white_0_0)] mask-exclude">
              <h3 className="mb-4 text-sm font-semibold text-gray-200">
                On This Page
              </h3>
              <nav className="space-y-1">
                {currentSection?.subsections.map((sub, idx) => (
                  <button
                    key={sub.id}
                    onClick={() => setActiveSubsection(idx)}
                    className={`block w-full text-left text-xs transition-colors py-1 ${
                      activeSubsection === idx
                        ? "font-semibold text-indigo-400"
                        : "text-gray-500 hover:text-gray-300"
                    }`}
                  >
                    {sub.title}
                  </button>
                ))}
              </nav>

              <div className="mt-6 border-t border-gray-700/50 pt-5">
                <p className="mb-3 text-sm font-semibold text-gray-200">
                  Need Help?
                </p>
                <ul className="space-y-2 text-xs">
                  <li>
                    <a href="/contact" className="text-indigo-400 transition-colors hover:text-indigo-300">
                      → Contact Support
                    </a>
                  </li>
                  <li>
                    <a href="/schedule-demo" className="text-indigo-400 transition-colors hover:text-indigo-300">
                      → Schedule a Demo
                    </a>
                  </li>
                  <li>
                    <a href="/free-trial" className="text-indigo-400 transition-colors hover:text-indigo-300">
                      → Start Free Trial
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </aside>
        </div>
      </div>
    </div>
  );
}
